import { Box, Text, ListItem, Heading, UnorderedList } from '@chakra-ui/react'
import { useRouter } from 'next/router'

const PrivacyPolicy = () => {
  const router = useRouter()
  const { locale } = router
  if (locale === 'en' || !locale) {
    return (
      <Box my='40px' fontSize='14px' lineHeight='24px'>
        <Heading my='8px' size='md' mb='20px'>
          Privacy Policy
        </Heading>
        <Text>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
          information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </Text>
        <Text>
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
          collection and use of information in accordance with this Privacy Policy.
        </Text>
        <Heading my='8px' size='sm'>
          Interpretation and Definitions
        </Heading>
        <Heading my='8px' size='xs'>
          Interpretation
        </Heading>
        <Text>
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The
          following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </Text>
        <Heading my='8px' size='xs'>
          Definitions
        </Heading>
        <Text>For the purposes of this Privacy Policy:</Text>
        <UnorderedList>
          <ListItem>
            <Text>
              <strong>Account</strong> means a unique account created for You to access our Service or parts of our
              Service.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with
              a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other
              securities entitled to vote for election of directors or other managing authority.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or
              &quot;Our&quot; in this Agreement) refers to Auth Demo App.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other
              device by a website, containing the details of Your browsing history on that website among its many uses.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Country</strong> refers to: Switzerland
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a
              digital tablet.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Personal Data</strong> is any information that relates to an identified or identifiable
              individual.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Service</strong> refers to the Website.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of
              the Company. It refers to third-party companies or individuals employed by the Company to facilitate the
              Service, to provide the Service on behalf of the Company, to perform services related to the Service or to
              assist the Company in analyzing how the Service is used.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the
              Service or from the Service infrastructure itself (for example, the duration of a page visit).
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Website</strong> refers to Auth Demo App, accessible from
              <a href='https://www.authdemoapp.com/' rel='external nofollow noopener noreferrer' target='_blank'>
                https://www.authdemoapp.com/
              </a>
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal
              entity on behalf of which such individual is accessing or using the Service, as applicable.
            </Text>
          </ListItem>
        </UnorderedList>
        <Heading my='8px' size='sm'>
          Collecting and Using Your Personal Data
        </Heading>
        <Heading my='8px' size='xs'>
          Types of Data Collected
        </Heading>
        <Text fontSize='16px' my='4px' fontWeight={600}>
          Personal Data
        </Text>
        <Text>
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that
          can be used to contact or identify You. Personally identifiable information may include, but is not limited
          to:
        </Text>
        <UnorderedList>
          <ListItem>
            <Text>Email address</Text>
          </ListItem>
          <ListItem>
            <Text>First name and last name</Text>
          </ListItem>
          <ListItem>
            <Text>Usage Data</Text>
          </ListItem>
        </UnorderedList>
        <Text fontSize='16px' my='4px' fontWeight={600}>
          Usage Data
        </Text>
        <Text>Usage Data is collected automatically when using the Service.</Text>
        <Text>
          Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser
          type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time
          spent on those pages, unique device identifiers and other diagnostic data.
        </Text>
        <Text>
          When You access the Service by or through a mobile device, We may collect certain information automatically,
          including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address
          of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique
          device identifiers and other diagnostic data.
        </Text>
        <Text>
          We may also collect information that Your browser sends whenever You visit our Service or when You access the
          Service by or through a mobile device.
        </Text>
        <Text fontSize='16px' my='4px' fontWeight={600}>
          Tracking Technologies and Cookies
        </Text>
        <Text>
          We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
          information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to
          improve and analyze Our Service. The technologies We use may include:
        </Text>
        <UnorderedList>
          <ListItem>
            <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can
            instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do
            not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your
            browser setting so that it will refuse Cookies, our Service may use Cookies.
          </ListItem>
          <ListItem>
            <strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic
            files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit
            the Company, for example, to count users who have visited those pages or opened an email and for other
            related website statistics (for example, recording the popularity of a certain section and verifying system
            and server integrity).
          </ListItem>
        </UnorderedList>
        <Text>
          Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your
          personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close
          Your web browser.
        </Text>
        <Text>We use both Session and Persistent Cookies for the purposes set out below:</Text>
        <UnorderedList>
          <ListItem>
            <Text>
              <strong>Necessary / Essential Cookies</strong>
            </Text>
            <Text>Type: Session Cookies</Text>
            <Text>Administered by: Us</Text>
            <Text>
              Purpose: These Cookies are essential to provide You with services available through the Website and to
              enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user
              accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use
              these Cookies to provide You with those services.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Cookies Policy / Notice Acceptance Cookies</strong>
            </Text>
            <Text>Type: Persistent Cookies</Text>
            <Text>Administered by: Us</Text>
            <Text>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Functionality Cookies</strong>
            </Text>
            <Text>Type: Persistent Cookies</Text>
            <Text>Administered by: Us</Text>
            <Text>
              Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering
              your login details or language preference. The purpose of these Cookies is to provide You with a more
              personal experience and to avoid You having to re-enter your preferences every time You use the Website.
            </Text>
          </ListItem>
        </UnorderedList>
        <Text>
          For more information about the cookies we use and your choices regarding cookies, please visit our Cookies
          Policy or the Cookies section of our Privacy Policy.
        </Text>
        <Heading my='8px' size='xs'>
          Use of Your Personal Data
        </Heading>
        <Text>The Company may use Personal Data for the following purposes:</Text>
        <UnorderedList>
          <ListItem>
            <Text>
              <strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The
              Personal Data You provide can give You access to different functionalities of the Service that are
              available to You as a registered user.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>For the performance of a contract:</strong> the development, compliance and undertaking of the
              purchase contract for the products, items or services You have purchased or of any other contract with Us
              through the Service.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms
              of electronic communication, such as a mobile application's push notifications regarding updates or
              informative communications related to the functionalities, products or contracted services, including the
              security updates, when necessary or reasonable for their implementation.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>To provide You</strong> with news, special offers and general information about other goods,
              services and events which we offer that are similar to those that you have already purchased or enquired
              about unless You have opted not to receive such information.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>To manage Your requests:</strong> To attend and manage Your requests to Us.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger,
              divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our
              assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which
              Personal Data held by Us about our Service users is among the assets transferred.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>For other purposes</strong>: We may use Your information for other purposes, such as data
              analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to
              evaluate and improve our Service, products, services, marketing and your experience.
            </Text>
          </ListItem>
        </UnorderedList>
        <Text>We may share Your personal information in the following situations:</Text>
        <UnorderedList>
          <ListItem>
            <strong>With Service Providers:</strong> We may share Your personal information with Service Providers to
            monitor and analyze the use of our Service, to contact You.
          </ListItem>
          <ListItem>
            <strong>For business transfers:</strong> We may share or transfer Your personal information in connection
            with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a
            portion of Our business to another company.
          </ListItem>
          <ListItem>
            <strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will
            require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other
            subsidiaries, joint venture partners or other companies that We control or that are under common control
            with Us.
          </ListItem>
          <ListItem>
            <strong>With business partners:</strong> We may share Your information with Our business partners to offer
            You certain products, services or promotions.
          </ListItem>
          <ListItem>
            <strong>With other users:</strong> when You share personal information or otherwise interact in the public
            areas with other users, such information may be viewed by all users and may be publicly distributed outside.
          </ListItem>
          <ListItem>
            <strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with
            Your consent.
          </ListItem>
        </UnorderedList>
        <Heading my='8px' size='xs'>
          Retention of Your Personal Data
        </Heading>
        <Text>
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this
          Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal
          obligations (for example, if we are required to retain your data to comply with applicable laws), resolve
          disputes, and enforce our legal agreements and policies.
        </Text>
        <Text>
          The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a
          shorter period of time, except when this data is used to strengthen the security or to improve the
          functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
        </Text>
        <Heading my='8px' size='xs'>
          Transfer of Your Personal Data
        </Heading>
        <Text>
          Your information, including Personal Data, is processed at the Company's operating offices and in any other
          places where the parties involved in the processing are located. It means that this information may be
          transferred to — and maintained on — computers located outside of Your state, province, country or other
          governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
        </Text>
        <Text>
          Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement
          to that transfer.
        </Text>
        <Text>
          The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in
          accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization
          or a country unless there are adequate controls in place including the security of Your data and other
          personal information.
        </Text>
        <Heading my='8px' size='xs'>
          Delete Your Personal Data
        </Heading>
        <Text>
          You have the right to delete or request that We assist in deleting the Personal Data that We have collected
          about You.
        </Text>
        <Text>
          Our Service may give You the ability to delete certain information about You from within the Service.
        </Text>
        <Text>
          You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one,
          and visiting the account settings section that allows you to manage Your personal information. You may also
          contact Us to request access to, correct, or delete any personal information that You have provided to Us.
        </Text>
        <Text>
          Please note, however, that We may need to retain certain information when we have a legal obligation or lawful
          basis to do so.
        </Text>
        <Heading my='8px' size='xs'>
          Disclosure of Your Personal Data
        </Heading>
        <Text fontSize='16px' my='4px' fontWeight={600}>
          Business Transactions
        </Text>
        <Text>
          If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We
          will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy
          Policy.
        </Text>
        <Text fontSize='16px' my='4px' fontWeight={600}>
          Law enforcement
        </Text>
        <Text>
          Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so
          by law or in response to valid requests by public authorities (e.g. a court or a government agency).
        </Text>
        <Text fontSize='16px' my='4px' fontWeight={600}>
          Other legal requirements
        </Text>
        <Text>
          The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
        </Text>
        <UnorderedList>
          <ListItem>Comply with a legal obligation</ListItem>
          <ListItem>Protect and defend the rights or property of the Company</ListItem>
          <ListItem>Prevent or investigate possible wrongdoing in connection with the Service</ListItem>
          <ListItem>Protect the personal safety of Users of the Service or the public</ListItem>
          <ListItem>Protect against legal liability</ListItem>
        </UnorderedList>
        <Heading my='8px' size='xs'>
          Security of Your Personal Data
        </Heading>
        <Text>
          The security of Your Personal Data is important to Us, but remember that no method of transmission over the
          Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means
          to protect Your Personal Data, We cannot guarantee its absolute security.
        </Text>
        <Heading my='8px' size='sm'>
          Children's Privacy
        </Heading>
        <Text>
          Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable
          information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child
          has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data
          from anyone under the age of 13 without verification of parental consent, We take steps to remove that
          information from Our servers.
        </Text>
        <Text>
          If We need to rely on consent as a legal basis for processing Your information and Your country requires
          consent from a parent, We may require Your parent's consent before We collect and use that information.
        </Text>
        <Heading my='8px' size='sm'>
          Links to Other Websites
        </Heading>
        <Text>
          Our Service may contain links to other websites that are not operated by Us. If You click on a third party
          link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of
          every site You visit.
        </Text>
        <Text>
          We have no control over and assume no responsibility for the content, privacy policies or practices of any
          third party sites or services.
        </Text>
        <Heading my='8px' size='sm'>
          Changes to this Privacy Policy
        </Heading>
        <Text>
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
          Privacy Policy on this page.
        </Text>
        <Text>
          We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming
          effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.
        </Text>
        <Text>
          You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are
          effective when they are posted on this page.
        </Text>
        <Heading my='8px' size='sm'>
          Contact Us
        </Heading>
        <Text>If you have any questions about this Privacy Policy, You can contact us:</Text>
        <UnorderedList>
          <ListItem>By email: slavalu74@gmail.com</ListItem>
        </UnorderedList>
      </Box>
    )
  }
  if (locale === 'de') {
    return (
      <Box my='40px' fontSize='14px' lineHeight='24px'>
        <Heading my='8px' size='md' mb='20px'>
          Datenschutzrichtlinie
        </Heading>
        <Text>
          Diese Datenschutzrichtlinie beschreibt unsere Richtlinien und Verfahren zur Erfassung, Nutzung und Offenlegung
          Ihrer Informationen, wenn Sie den Dienst nutzen und informiert Sie über Ihre Datenschutzrechte und wie das
          Gesetz Sie schützt.
        </Text>
        <Text>
          Wir verwenden Ihre persönlichen Daten, um den Dienst bereitzustellen und zu verbessern. Durch die Nutzung des
          Dienstes stimmen Sie der Erfassung und Verwendung von Informationen in Übereinstimmung mit dieser
          Datenschutzrichtlinie zu.
        </Text>
        <Heading my='8px' size='sm'>
          Auslegung und Definitionen
        </Heading>
        <Heading my='8px' size='xs'>
          Auslegung
        </Heading>
        <Text>
          Die Wörter, bei denen der erste Buchstabe großgeschrieben ist, haben Bedeutungen, die unter den folgenden
          Bedingungen definiert sind. Die folgenden Definitionen haben unabhängig davon, ob sie im Singular oder im
          Plural erscheinen, dieselbe Bedeutung.
        </Text>
        <Heading my='8px' size='xs'>
          Definitionen
        </Heading>
        <Text>Zu den Zwecken dieser Datenschutzrichtlinie:</Text>
        <UnorderedList>
          <ListItem>
            <Text>
              <strong>Konto</strong> bedeutet ein einzigartiges Konto, das für Sie erstellt wurde, um auf unseren Dienst
              oder Teile unseres Dienstes zuzugreifen.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Affiliate</strong> bedeutet eine Entität, die eine Partei kontrolliert, von einer Partei
              kontrolliert wird oder unter gemeinsamer Kontrolle mit einer Partei steht, wobei "Kontrolle" den Besitz
              von 50 % oder mehr der Anteile, Beteiligungen oder anderen Wertpapieren bedeutet, die zum Wählen von
              Direktoren oder einer anderen Verwaltungsbehörde berechtigen.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Unternehmen</strong> (bezeichnet als "das Unternehmen", "Wir", "Uns" oder "Unser" in dieser
              Vereinbarung) bezieht sich auf Auth Demo App.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Cookies</strong> sind kleine Dateien, die von einer Website auf Ihrem Computer, Mobilgerät oder
              einem anderen Gerät platziert werden und unter anderem Einzelheiten zu Ihrer Browserhistorie auf dieser
              Website enthalten.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Land</strong> bezieht sich auf: Schweiz
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Gerät</strong> bezeichnet jedes Gerät, das auf den Dienst zugreifen kann, wie z.B. ein Computer,
              ein Mobiltelefon oder ein digitales Tablet.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Personenbezogene Daten</strong> sind alle Informationen, die sich auf eine identifizierte oder
              identifizierbare natürliche Person beziehen.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Dienst</strong> bezieht sich auf die Webseite.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Dienstanbieter</strong> bedeutet jede natürliche oder juristische Person, die im Auftrag des
              Unternehmens Daten verarbeitet. Es bezieht sich auf Drittanbieterunternehmen oder Einzelpersonen, die vom
              Unternehmen beschäftigt werden, um den Dienst zu erleichtern, den Dienst im Auftrag des Unternehmens
              bereitzustellen, Dienstleistungen im Zusammenhang mit dem Dienst auszuführen oder das Unternehmen bei der
              Analyse der Nutzung des Dienstes zu unterstützen.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Nutzungsdaten</strong> beziehen sich auf Daten, die automatisch gesammelt werden, entweder durch
              die Nutzung des Dienstes oder aus der Infrastruktur des Dienstes selbst (zum Beispiel die Dauer eines
              Seitenbesuchs).
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Website</strong> bezieht sich auf Auth Demo App, zugänglich von
              <a href='https://www.authdemoapp.com/' rel='external nofollow noopener noreferrer' target='_blank'>
                https://www.authdemoapp.com/
              </a>
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Sie</strong> bezeichnet die einzelne Person, die den Dienst nutzt oder darauf zugreift, oder das
              Unternehmen oder eine andere juristische Einheit, in deren Auftrag eine solche Person den Dienst nutzt
              oder darauf zugreift.
            </Text>
          </ListItem>
        </UnorderedList>
        <Heading my='8px' size='sm'>
          Sammeln und Verwenden Ihrer persönlichen Daten
        </Heading>
        <Heading my='8px' size='xs'>
          Arten von gesammelten Daten
        </Heading>
        <Text fontSize='16px' my='4px' fontWeight={600}>
          Persönliche Daten
        </Text>
        <Text>
          Während der Nutzung unseres Dienstes bitten wir Sie möglicherweise um bestimmte persönlich identifizierbare
          Informationen, die zur Kontaktaufnahme oder Identifizierung Ihrer Person verwendet werden können. Zu solchen
          persönlich identifizierbaren Informationen können gehören, sind jedoch nicht darauf beschränkt:
        </Text>
        <UnorderedList>
          <ListItem>
            <Text>E-Mail-Adresse</Text>
          </ListItem>
          <ListItem>
            <Text>Vorname und Nachname</Text>
          </ListItem>
          <ListItem>
            <Text>Nutzungsdaten</Text>
          </ListItem>
        </UnorderedList>
        <Text fontSize='16px' my='4px' fontWeight={600}>
          Nutzungsdaten
        </Text>
        <Text>Nutzungsdaten werden automatisch erfasst, wenn Sie den Dienst verwenden.</Text>
        <Text>
          Nutzungsdaten können Informationen wie die Internetprotokolladresse Ihres Geräts (z.B. IP-Adresse), den
          Browsertyp, die Browserversion, die von Ihnen besuchten Seiten unseres Dienstes, die Uhrzeit und das Datum
          Ihres Besuchs, die auf diesen Seiten verbrachte Zeit, eindeutige Gerätekennungen und andere diagnostische
          Daten umfassen.
        </Text>
        <Text>
          Wenn Sie auf den Dienst über ein mobiles Gerät zugreifen, können wir bestimmte Informationen automatisch
          erfassen, einschließlich, jedoch nicht beschränkt auf den Typ des von Ihnen verwendeten mobilen Geräts, die
          eindeutige Kennung Ihres mobilen Geräts, die IP-Adresse Ihres mobilen Geräts, Ihr mobiles Betriebssystem, den
          Typ des von Ihnen verwendeten mobilen Internetbrowsers, eindeutige Gerätekennungen und andere diagnostische
          Daten.
        </Text>
        <Text>
          Wir können auch Informationen erfassen, die Ihr Browser sendet, wenn Sie unseren Dienst besuchen oder wenn Sie
          auf den Dienst über ein mobiles Gerät zugreifen.
        </Text>
        <Text fontSize='16px' my='4px' fontWeight={600}>
          Tracking-Technologien und Cookies
        </Text>
        <Text>
          Wir verwenden Cookies und ähnliche Tracking-Technologien, um die Aktivitäten auf unserem Dienst zu verfolgen
          und bestimmte Informationen zu speichern. Die verwendeten Tracking-Technologien sind Beacons, Tags und Skripte
          zur Erfassung und Verfolgung von Informationen sowie zur Verbesserung und Analyse unseres Dienstes. Die von
          uns verwendeten Technologien können umfassen:
        </Text>
        <UnorderedList>
          <ListItem>
            <strong>Cookies oder Browser-Cookies.</strong> Ein Cookie ist eine kleine Datei, die auf Ihrem Gerät
            gespeichert wird. Sie können Ihren Browser anweisen, alle Cookies abzulehnen oder anzuzeigen, wenn ein
            Cookie gesendet wird. Wenn Sie jedoch Cookies nicht akzeptieren, können Sie einige Teile unseres Dienstes
            möglicherweise nicht nutzen. Sofern Sie Ihre Browsereinstellungen nicht so angepasst haben, dass Cookies
            abgelehnt werden, kann unser Dienst Cookies verwenden.
          </ListItem>
          <ListItem>
            <strong>Web-Beacons.</strong> Bestimmte Abschnitte unseres Dienstes und unserer E-Mails können kleine
            elektronische Dateien enthalten, die als Web-Beacons bezeichnet werden (auch als Clear GIFs, Pixel-Tags und
            Ein-Pixel-GIFs bezeichnet) und es dem Unternehmen ermöglichen, beispielsweise Benutzer zu zählen, die diese
            Seiten besucht haben oder eine E-Mail geöffnet haben, sowie andere damit verbundene Website-Statistiken (z.
            B. die Popularität eines bestimmten Abschnitts und die Überprüfung der Integrität von System und Server).
          </ListItem>
        </UnorderedList>
        <Text>
          Cookies können "Persistent" oder "Session" Cookies sein. Persistent Cookies verbleiben auf Ihrem persönlichen
          Computer oder Mobilgerät, wenn Sie offline gehen, während Session Cookies gelöscht werden, sobald Sie Ihren
          Webbrowser schließen.
        </Text>
        <Text>Wir verwenden sowohl Session- als auch Persistent-Cookies für die unten aufgeführten Zwecke:</Text>
        <UnorderedList>
          <ListItem>
            <Text>
              <strong>Notwendige / wesentliche Cookies</strong>
            </Text>
            <Text>Type: Session Cookies</Text>
            <Text>Verwaltet von: Uns</Text>
            <Text>
              Zweck: Diese Cookies sind unerlässlich, um Ihnen die über die Website verfügbaren Dienste bereitzustellen
              und es Ihnen zu ermöglichen, einige ihrer Funktionen zu nutzen. Sie helfen dabei, Benutzer zu
              authentifizieren und einen betrügerischen Gebrauch von Benutzerkonten zu verhindern. Ohne diese Cookies
              können die von Ihnen angeforderten Dienste nicht bereitgestellt werden, und wir verwenden diese Cookies
              nur, um Ihnen diese Dienste bereitzustellen.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Cookies-Richtlinie / Zustimmungs-Cookies</strong>
            </Text>
            <Text>Type: Persistent Cookies</Text>
            <Text>Verwaltet von: Uns</Text>
            <Text>
              Zweck: Diese Cookies identifizieren, ob Benutzer die Verwendung von Cookies auf der Website akzeptiert
              haben.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Funktionscookies</strong>
            </Text>
            <Text>Type: Persistent Cookies</Text>
            <Text>Verwaltet von: Uns</Text>
            <Text>
              Zweck: Diese Cookies ermöglichen es uns, Ihre Auswahl zu speichern, wenn Sie die Website nutzen, z. B.
              Ihre Anmeldedaten oder Sprachpräferenz. Diese Cookies sollen Ihnen ein persönlicheres Erlebnis bieten und
              verhindern, dass Sie bei jeder Nutzung der Website erneut Ihre Präferenzen eingeben müssen.
            </Text>
          </ListItem>
        </UnorderedList>
        <Text>
          Weitere Informationen über die von uns verwendeten Cookies und Ihre Auswahlmöglichkeiten in Bezug auf Cookies
          finden Sie in unserer Cookie-Richtlinie oder im Cookie-Abschnitt unserer Datenschutzrichtlinie.
        </Text>
        <Heading my='8px' size='xs'>
          Verwendung Ihrer persönlichen Daten
        </Heading>
        <Text>Das Unternehmen kann persönliche Daten für folgende Zwecke verwenden:</Text>
        <UnorderedList>
          <ListItem>
            <Text>
              <strong>Um unseren Dienst bereitzustellen und aufrechtzuerhalten</strong>, einschließlich der Überwachung
              der Nutzung unseres Dienstes.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Zur Verwaltung Ihres Kontos:</strong> zur Verwaltung Ihrer Registrierung als Benutzer des
              Dienstes. Die von Ihnen bereitgestellten persönlichen Daten ermöglichen Ihnen den Zugriff auf verschiedene
              Funktionen des Dienstes, die Ihnen als registriertem Benutzer zur Verfügung stehen.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Zur Erfüllung eines Vertrags:</strong> zur Entwicklung, Einhaltung und Durchführung des
              Kaufvertrags für die von Ihnen gekauften Produkte, Artikel oder Dienstleistungen oder eines anderen
              Vertrags mit uns über den Dienst.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Um Sie zu kontaktieren:</strong> Um Sie per E-Mail, Telefonanrufe, SMS oder andere äquivalente
              Formen der elektronischen Kommunikation zu kontaktieren, wie Push-Benachrichtigungen einer mobilen
              Anwendung zu Aktualisierungen oder informativen Mitteilungen im Zusammenhang mit den Funktionen, Produkten
              oder in Anspruch genommenen Dienstleistungen, einschließlich Sicherheitsaktualisierungen, wenn dies für
              deren Umsetzung erforderlich oder vernünftig ist.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Um Ihnen</strong> Nachrichten, Sonderangebote und allgemeine Informationen zu anderen Waren,
              Dienstleistungen und Veranstaltungen anzubieten, die wir anbieten, und die ähnlich sind wie diejenigen,
              die Sie bereits gekauft oder angefragt haben, sofern Sie nicht auf den Erhalt solcher Informationen
              verzichtet haben.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Zur Verwaltung Ihrer Anfragen:</strong> Zur Bearbeitung und Verwaltung Ihrer Anfragen an uns.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Für Geschäftsübertragungen:</strong> Wir können Ihre Informationen verwenden, um eine Fusion,
              einen Verkauf, eine Umstrukturierung, eine Reorganisation, eine Auflösung oder einen anderen Verkauf oder
              die Übertragung eines Teils oder aller unserer Vermögenswerte zu bewerten oder durchzuführen, sei es als
              laufendes Geschäft oder im Rahmen eines Konkurs-, Liquidations- oder ähnlichen Verfahrens, bei dem von uns
              gehaltene persönliche Daten unserer Dienstnutzer zu den übertragenen Vermögenswerten gehören.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>Zu anderen Zwecken</strong>: Wir können Ihre Informationen für andere Zwecke verwenden, wie z. B.
              Datenanalyse, Identifizierung von Nutzungstrends, Bestimmung der Wirksamkeit unserer Werbekampagnen und
              zur Bewertung und Verbesserung unseres Dienstes, unserer Produkte, Dienstleistungen, Marketingaktivitäten
              und Ihres Erlebnisses.
            </Text>
          </ListItem>
        </UnorderedList>
        <Text>Wir können Ihre persönlichen Informationen in folgenden Situationen teilen:</Text>
        <UnorderedList>
          <ListItem>
            <strong>Mit Dienstleistern:</strong> Wir können Ihre persönlichen Informationen mit Dienstleistern teilen,
            um die Nutzung unseres Dienstes zu überwachen und zu analysieren sowie um Sie zu kontaktieren.
          </ListItem>
          <ListItem>
            <strong>Für Unternehmensübertragungen:</strong> Wir können Ihre persönlichen Informationen im Zusammenhang
            mit einer Fusion, dem Verkauf von Unternehmensvermögenswerten, der Finanzierung oder der Übernahme unseres
            gesamten oder eines Teils unseres Unternehmens durch ein anderes Unternehmen teilen oder übertragen.
          </ListItem>
          <ListItem>
            <strong>Mit Tochtergesellschaften:</strong> Wir können Ihre Informationen mit unseren Tochtergesellschaften
            teilen, in diesem Fall werden wir von diesen Tochtergesellschaften verlangen, diese Datenschutzrichtlinie zu
            respektieren. Zu den Tochtergesellschaften gehören unsere Muttergesellschaft und alle anderen
            Tochtergesellschaften, Joint-Venture-Partner oder andere Unternehmen, die von uns kontrolliert werden oder
            die sich unter unserer gemeinsamen Kontrolle befinden.
          </ListItem>
          <ListItem>
            <strong>Mit Geschäftspartnern:</strong> Wir können Ihre Informationen mit unseren Geschäftspartnern teilen,
            um Ihnen bestimmte Produkte, Dienstleistungen oder Aktionen anzubieten.
          </ListItem>
          <ListItem>
            <strong>Mit anderen Nutzern:</strong> Wenn Sie persönliche Informationen teilen oder anderweitig in den
            öffentlichen Bereichen mit anderen Nutzern interagieren, können diese Informationen von allen Nutzern
            eingesehen und öffentlich verbreitet werden.
          </ListItem>
          <ListItem>
            <strong>Mit Ihrer Zustimmung</strong>: Wir können Ihre persönlichen Informationen für jeden anderen Zweck
            mit Ihrer Zustimmung offenlegen.
          </ListItem>
        </UnorderedList>
        <Heading my='8px' size='xs'>
          Aufbewahrung Ihrer persönlichen Daten
        </Heading>
        <Text>
          Das Unternehmen wird Ihre persönlichen Daten nur so lange aufbewahren, wie dies für die in dieser
          Datenschutzrichtlinie festgelegten Zwecke erforderlich ist. Wir werden Ihre persönlichen Daten in dem Umfang
          aufbewahren und verwenden, der zur Erfüllung unserer rechtlichen Verpflichtungen erforderlich ist (z. B. wenn
          wir gesetzlich verpflichtet sind, Ihre Daten aufzubewahren, um geltende Gesetze einzuhalten), Streitigkeiten
          beizulegen und unsere rechtlichen Vereinbarungen und Richtlinien durchzusetzen.
        </Text>
        <Text>
          Das Unternehmen wird auch Nutzungsdaten zu internen Analysezwecken aufbewahren. Nutzungsdaten werden in der
          Regel für einen kürzeren Zeitraum aufbewahrt, es sei denn, diese Daten werden zur Stärkung der Sicherheit oder
          zur Verbesserung der Funktionalität unseres Dienstes verwendet, oder wir sind gesetzlich verpflichtet, diese
          Daten über längere Zeiträume aufzubewahren.
        </Text>
        <Heading my='8px' size='xs'>
          Übertragung Ihrer persönlichen Daten
        </Heading>
        <Text>
          Ihre Informationen, einschließlich persönlicher Daten, werden in den betrieblichen Büros des Unternehmens und
          an anderen Orten verarbeitet, an denen sich die an der Verarbeitung beteiligten Parteien befinden. Dies
          bedeutet, dass diese Informationen an Computer außerhalb Ihres Bundeslandes, Ihrer Provinz, Ihres Landes oder
          Ihrer anderen staatlichen Gerichtsbarkeit übertragen und aufbewahrt werden können, in denen die
          Datenschutzgesetze von denen in Ihrer Gerichtsbarkeit abweichen können.
        </Text>
        <Text>
          Ihre Zustimmung zu dieser Datenschutzrichtlinie und Ihre Übermittlung solcher Informationen stellen Ihre
          Zustimmung zu dieser Übertragung dar.
        </Text>
        <Text>
          Das Unternehmen wird alle vernünftigerweise erforderlichen Schritte unternehmen, um sicherzustellen, dass Ihre
          Daten sicher und in Übereinstimmung mit dieser Datenschutzrichtlinie behandelt werden, und keine Übertragung
          Ihrer persönlichen Daten wird an eine Organisation oder ein Land erfolgen, es sei denn, es liegen angemessene
          Kontrollen vor, einschließlich der Sicherheit Ihrer Daten und anderer persönlicher Informationen.
        </Text>
        <Heading my='8px' size='xs'>
          Löschen Ihrer persönlichen Daten
        </Heading>
        <Text>
          Sie haben das Recht, die Löschung oder die Anfrage zu fordern, dass wir bei der Löschung der von uns über Sie
          gesammelten persönlichen Daten helfen.
        </Text>
        <Text>
          Unser Dienst kann Ihnen die Möglichkeit geben, bestimmte Informationen über Sie innerhalb des Dienstes zu
          löschen.
        </Text>
        <Text>
          Sie können Ihre Informationen jederzeit aktualisieren, ändern oder löschen, indem Sie sich in Ihr Konto
          einloggen, sofern Sie eines haben, und den Abschnitt "Kontoeinstellungen" besuchen, der es Ihnen ermöglicht,
          Ihre persönlichen Informationen zu verwalten. Sie können uns auch kontaktieren, um Zugriff auf, Korrektur oder
          Löschung von Ihnen bereitgestellten persönlichen Informationen zu beantragen.
        </Text>
        <Text>
          Bitte beachten Sie jedoch, dass wir bestimmte Informationen aufbewahren müssen, wenn wir dazu aufgrund einer
          rechtlichen Verpflichtung oder eines rechtmäßigen Grundes verpflichtet sind.
        </Text>
        <Heading my='8px' size='xs'>
          Offenlegung Ihrer persönlichen Daten
        </Heading>
        <Text fontSize='16px' my='4px' fontWeight={600}>
          Geschäftliche Transaktionen
        </Text>
        <Text>
          Wenn das Unternehmen an einer Fusion, einem Erwerb oder einem Verkauf von Vermögenswerten beteiligt ist,
          können Ihre persönlichen Daten übertragen werden. Wir werden Sie benachrichtigen, bevor Ihre persönlichen
          Daten übertragen werden und einer anderen Datenschutzrichtlinie unterliegen.
        </Text>
        <Text fontSize='16px' my='4px' fontWeight={600}>
          Strafverfolgung
        </Text>
        <Text>
          Unter bestimmten Umständen kann das Unternehmen gesetzlich verpflichtet sein, Ihre persönlichen Daten
          offenzulegen, wenn dies von Gesetzes wegen oder aufgrund gültiger Anfragen von öffentlichen Behörden (z. B.
          Gericht oder Regierungsbehörde) erforderlich ist.
        </Text>
        <Text fontSize='16px' my='4px' fontWeight={600}>
          Andere rechtliche Anforderungen
        </Text>
        <Text>
          Das Unternehmen kann Ihre persönlichen Daten in gutem Glauben offenlegen, wenn eine solche Handlung notwendig
          ist, um:
        </Text>
        <UnorderedList>
          <ListItem>Einer rechtlichen Verpflichtung nachkommen</ListItem>
          <ListItem>Die Rechte oder das Eigentum des Unternehmens schützen und verteidigen</ListItem>
          <ListItem>Mögliche Verfehlungen im Zusammenhang mit dem Dienst verhindern oder untersuchen</ListItem>
          <ListItem>Die persönliche Sicherheit der Nutzer des Dienstes oder der Öffentlichkeit schützen</ListItem>
          <ListItem>Sich gegen rechtliche Haftung schützen</ListItem>
        </UnorderedList>
        <Heading my='8px' size='xs'>
          Sicherheit Ihrer persönlichen Daten
        </Heading>
        <Text>
          Die Sicherheit Ihrer persönlichen Daten ist uns wichtig, aber bitte beachten Sie, dass keine Methode der
          Übertragung über das Internet oder der elektronischen Speicherung zu 100 % sicher ist. Obwohl wir uns bemühen,
          kommerziell akzeptable Mittel zum Schutz Ihrer persönlichen Daten zu verwenden, können wir deren absolute
          Sicherheit nicht garantieren.
        </Text>
        <Heading my='8px' size='sm'>
          Datenschutz von Kindern
        </Heading>
        <Text>
          Unser Dienst richtet sich nicht an Personen unter 13 Jahren. Wir sammeln nicht wissentlich personenbezogene
          Informationen von Personen unter 13 Jahren. Wenn Sie ein Elternteil oder Erziehungsberechtigter sind und
          wissen, dass Ihr Kind uns personenbezogene Daten zur Verfügung gestellt hat, kontaktieren Sie uns bitte. Wenn
          uns bekannt wird, dass wir personenbezogene Daten von Personen unter 13 Jahren ohne Überprüfung der
          elterlichen Zustimmung gesammelt haben, ergreifen wir Maßnahmen, um diese Informationen von unseren Servern zu
          entfernen.
        </Text>
        <Text>
          Wenn wir uns auf die Zustimmung als Rechtsgrundlage für die Verarbeitung Ihrer Informationen verlassen müssen
          und Ihr Land die Zustimmung eines Elternteils erfordert, können wir die Zustimmung Ihres Elternteils
          benötigen, bevor wir diese Informationen sammeln und verwenden.
        </Text>
        <Heading my='8px' size='sm'>
          Links zu anderen Websites
        </Heading>
        <Text>
          Unser Dienst kann Links zu anderen Websites enthalten, die nicht von uns betrieben werden. Wenn Sie auf einen
          Link von Dritten klicken, werden Sie zu der Website dieses Dritten weitergeleitet. Wir empfehlen Ihnen
          dringend, die Datenschutzrichtlinie jeder von Ihnen besuchten Website zu überprüfen.
        </Text>
        <Text>
          Wir haben keine Kontrolle über und übernehmen keine Verantwortung für den Inhalt, die Datenschutzrichtlinien
          oder Praktiken von Websites oder Diensten Dritter.
        </Text>
        <Heading my='8px' size='sm'>
          Änderungen an dieser Datenschutzrichtlinie
        </Heading>
        <Text>
          Wir können unsere Datenschutzrichtlinie von Zeit zu Zeit aktualisieren. Wir werden Sie über Änderungen
          informieren, indem wir die neue Datenschutzrichtlinie auf dieser Seite veröffentlichen.
        </Text>
        <Text>
          Wir werden Sie per E-Mail und/oder durch einen prominenten Hinweis auf unserem Dienst darüber informieren,
          bevor die Änderung in Kraft tritt, und das Datum "Zuletzt aktualisiert" oben auf dieser Datenschutzrichtlinie
          aktualisieren.
        </Text>
        <Text>
          Sie werden empfohlen, diese Datenschutzrichtlinie regelmäßig auf Änderungen zu überprüfen. Änderungen an
          dieser Datenschutzrichtlinie werden wirksam, wenn sie auf dieser Seite veröffentlicht werden.
        </Text>
        <Heading my='8px' size='sm'>
          Kontaktieren Sie uns
        </Heading>
        <Text>Wenn Sie Fragen zu dieser Datenschutzrichtlinie haben, können Sie uns kontaktieren:</Text>
        <UnorderedList>
          <ListItem>Per E-Mail: slavalu74@gmail.com</ListItem>
        </UnorderedList>
      </Box>
    )
  }
}

export default PrivacyPolicy
